export const blogPosts = [
  {
    id: 1,
    slug: 'behind-the-beans-ethiopian-sourcing',
    title: 'Behind the Beans: Our Ethiopian Sourcing Journey',
    excerpt: 'Travel with us to the highlands of Ethiopia – where we met the farmers behind our most popular single-origin.',
    category: 'Behind the Beans',
    author: 'Maya Chen',
    date: 'June 15, 2026',
    readTime: '4 min read',
    image: 'https://images.unsplash.com/photo-1587049352847-1bc349e5a965?w=800&h=600&fit=crop&crop=center',
    content: 'Full blog content here...',
  },
  {
    id: 2,
    slug: 'barista-spotlight-alex-rivera',
    title: 'Barista Spotlight: Alex Rivera',
    excerpt: 'Meet our head roaster – his journey from a small cart to mastering the art of single-origin roasting.',
    category: 'Barista Spotlights',
    author: 'Alex Rivera',
    date: 'June 10, 2026',
    readTime: '3 min read',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&h=600&fit=crop&crop=face',
    content: 'Full blog content here...',
  },
  {
    id: 3,
    slug: 'dehradun-local-coffee-guide',
    title: 'Dehradun Local: Our Coffee Community Guide',
    excerpt: 'Discover the best coffee spots, local events, and hidden gems in our beloved city – as seen through our eyes.',
    category: 'Local Guides & Events',
    author: 'Elena Martinez',
    date: 'June 5, 2026',
    readTime: '5 min read',
    image: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=800&h=600&fit=crop&crop=center',
    content: 'Full blog content here...',
  },
  {
    id: 4,
    slug: 'perfect-pour-over-tutorial',
    title: 'Brewing 101: The Perfect Pour-Over',
    excerpt: 'Step-by-step guide to mastering the pour-over method at home – with pro tips from our head barista.',
    category: 'Brewing Tutorials',
    author: 'James Park',
    date: 'May 28, 2026',
    readTime: '6 min read',
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&h=600&fit=crop&crop=center',
    content: 'Full blog content here...',
  },
  {
    id: 5,
    slug: 'summer-cold-brew-collection',
    title: 'New Menu: Summer Cold Brew Collection',
    excerpt: 'Beat the heat with our new cold brew lineup – featuring nitro, vanilla, and a special seasonal twist.',
    category: 'New Menu Announcements',
    author: 'Maya Chen',
    date: 'May 20, 2026',
    readTime: '3 min read',
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&h=600&fit=crop&crop=center',
    content: 'Full blog content here...',
  },
  {
    id: 6,
    slug: 'barista-spotlight-elena-martinez',
    title: 'Barista Spotlight: Elena Martinez',
    excerpt: 'From coffee cart to community manager – Elena shares her favorite drinks and what makes our café special.',
    category: 'Barista Spotlights',
    author: 'Elena Martinez',
    date: 'May 15, 2026',
    readTime: '3 min read',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=800&h=600&fit=crop&crop=face',
    content: 'Full blog content here...',
  },
];